/**
 * Seeds the Draft Night Challenge game + its 4 mini-games (handoff §4).
 *
 * The mock_lottery pool (top 50 minus Suigo = 49 slugs) is built from the master
 * CSV so it can never drift from src/lib/prospects.ts — hand-entering 49 slugs in
 * the Supabase table editor is exactly the error this avoids.
 *
 * Two modes:
 *   npx tsx scripts/seed-draft-night.ts            # prints idempotent SQL to stdout
 *   npx tsx scripts/seed-draft-night.ts --execute  # writes via the service role
 *                                                   # (needs NEXT_PUBLIC_SUPABASE_URL
 *                                                   #  + SUPABASE_SERVICE_ROLE_KEY)
 * See scripts/DRAFT_NIGHT_APPLY.md.
 */
import { getAllProspects } from "../src/lib/prospects";
import {
  GAME_SLUG,
  buildMockLotteryPool,
  draftedHigherConfig,
  firstRoundConfig,
  guardOrderConfig,
  mockLotteryConfig,
} from "../src/lib/draftNight/config";
import type { DnMiniGameKey, DnMiniGameType } from "../src/types/database";

// First-round tip: Jun 23 2026, 8 PM ET (EDT, UTC-4) = 2026-06-24T00:00:00Z.
const LOCK_AT = "2026-06-24T00:00:00.000Z";
const TITLE = "FHE Draft Night Challenge";

interface MiniRow {
  key: DnMiniGameKey;
  type: DnMiniGameType;
  sort: number;
  config: unknown;
}

function buildMiniGames(): MiniRow[] {
  const lotteryPool = buildMockLotteryPool(getAllProspects().map((p) => p.slug));
  // Friction-ascending display order (handoff §3): instant-momentum first,
  // the marquee self-draft last.
  return [
    { key: "drafted_higher", type: "single_pick", sort: 0, config: draftedHigherConfig },
    { key: "first_round", type: "multi_select", sort: 1, config: firstRoundConfig },
    { key: "guard_order", type: "rank_order", sort: 2, config: guardOrderConfig },
    { key: "mock_lottery", type: "rank_order", sort: 3, config: mockLotteryConfig(lotteryPool) },
  ];
}

function sqlStr(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function printSql(minis: MiniRow[]): void {
  const values = minis
    .map(
      (m) =>
        `    (${sqlStr(m.key)}, ${sqlStr(m.type)}, ${m.sort}, ${sqlStr(
          JSON.stringify(m.config),
        )})`,
    )
    .join(",\n");

  const sql = `-- Draft Night seed (generated by scripts/seed-draft-night.ts). Idempotent.
with g as (
  insert into public.dn_games (slug, title, status, lock_at)
  values (${sqlStr(GAME_SLUG)}, ${sqlStr(TITLE)}, 'live', ${sqlStr(LOCK_AT)})
  on conflict (slug) do update
    set title = excluded.title, status = excluded.status, lock_at = excluded.lock_at
  returning id
)
insert into public.dn_mini_games (game_id, key, type, sort, config)
select g.id, v.key::dn_mini_game_key, v.type::dn_mini_game_type, v.sort, v.config::jsonb
from g, (values
${values}
) as v(key, type, sort, config)
on conflict (game_id, key) do update
  set type = excluded.type, sort = excluded.sort, config = excluded.config;
`;
  console.log(sql);
}

async function execute(minis: MiniRow[]): Promise<void> {
  // Imported lazily so the default (SQL-print) path needs no env vars.
  const { createAdminClient } = await import("../src/utils/supabase/admin");
  const admin = createAdminClient();

  const { data: game, error: gameErr } = await admin
    .from("dn_games")
    .upsert(
      { slug: GAME_SLUG, title: TITLE, status: "live", lock_at: LOCK_AT },
      { onConflict: "slug" },
    )
    .select("id")
    .single();
  if (gameErr || !game) throw gameErr ?? new Error("game upsert returned no row");

  const { error: miniErr } = await admin.from("dn_mini_games").upsert(
    minis.map((m) => ({
      game_id: game.id,
      key: m.key,
      type: m.type,
      sort: m.sort,
      config: m.config as never,
    })),
    { onConflict: "game_id,key" },
  );
  if (miniErr) throw miniErr;

  console.error(`Seeded ${GAME_SLUG} (${game.id}) with ${minis.length} mini-games.`);
}

async function main() {
  const minis = buildMiniGames();
  if (process.argv.includes("--execute")) {
    await execute(minis);
  } else {
    printSql(minis);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
